---
- name: include_role with apply
  hosts: web
  gather_facts: false
  tasks:
    - name: Include webapp
      ansible.builtin.include_role:
        name: webapp
        apply:
          tags: deploy
      tags: deploy
